server:
  port: 2070
  address: 0.0.0.0

dubbo:
  application:
    name: alipay
  registry:
    address: 192.168.156.128:2181
    protocol: zookeeper
    check: off
  scan:
    base-packages: com.lewo.zmail.pay.service
  consumer:
    check: off
  protocol:
    port: 20887
    name: dubbo

spring:
  # 默认P2P模式，开启事务，确认模式为自动确认
  activemq:
    broker-url: tcp://192.168.156.128:61616
    user: admin
    password: admin
    close-timeout: 15s   # 在考虑结束之前等待的时间
    in-memory: true      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    non-blocking-redelivery: false  # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    # 等待消费者调用acknowledge()进行响应的时间。
    # 如果超过该时间provider还没收到consumer的告知，
    # 发送消息的方法将报requestTimeOut异常，而且消息还要入死信。
    # 最好设置为0，即永远等待，这样就不害怕p-c之间的网络阻塞了。
    send-timeout: 0
    pool:
      enabled: true
      max-connections: 10   #连接池最大连接数
      idle-timeout: 30000   #空闲的连接过期时间，默认为30秒
    packages:
      trust-all: true
#  所有消费者切换为pub-sub模式
#  jms:
#    pub-sub-domain: true


  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/zmail?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.156.128
    port: 6379
    password: godz1995
    timeout: 3000
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 10
        min-idle: 0
  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #设置非严格模式
    mode: LEGACYHTML5

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lewo.zmall.model
