#认证中心，服务调用user-service
server:
  port: 2050
  address: 0.0.0.0

dubbo:
  application:
    name: authentication-web
  registry:
    address: 192.168.156.128:2181
    protocol: zookeeper
  #  Whether to check if register center is available when boot up
    check: off
  consumer:
    check: off

spring:
  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #设置非严格模式
    mode: LEGACYHTML5
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.156.128
    port: 6379
    password: godz1995
    timeout: 3000
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 10
        min-idle: 0
