server:
  port: 2020
  address: 0.0.0.0

logging:
  level: info

spring:
  dubbo:
    application: item-web
    registry:
      address: 192.168.156.128:2181
    base-package: com.lewo.zmail.item.controller

  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #设置非严格模式
    mode: LEGACYHTML5

  resources:
    #设置静态资源路径
#    static-locations: classpath:/static/image


#    Dubbo 使用RPC通信标准化规范:
#    编写接口 —> 提供者将实现接口的service将服务注册到zookeeper注册中心 —> 消费者在服务中心引用提供者实现的接口

