server:
  port: 2020
  address: 0.0.0.0

dubbo:
  application:
    name: item-web
  registry:
    address: zookeeper://192.168.156.128:2181



spring:
  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #设置非严格模式
    mode: LEGACYHTML5
  main:
    allow-bean-definition-overriding: true
  resources:
    #设置静态资源路径
#    static-locations: classpath:/static/image


#    Dubbo 使用RPC通信标准化规范:
#    编写接口 —> 提供者将实现接口的service将服务注册到zookeeper注册中心 —> 消费者在服务中心引用提供者实现的接口

