server:
  port: 2010
  address: 0.0.0.0

dubbo:
  application:
    name: manage-web
  registry:
    address: 192.168.156.128
    protocol: zookeeper
    port: 2181


spring:
  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #设置非严格模式
    mode: LEGACYHTML5
  main:
    allow-bean-definition-overriding: true